version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: sports_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sportsdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: sports_backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/sportsdb
    depends_on:
      - db
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    container_name: sports_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3001

volumes:
  postgres_data:
    driver: local
